version: '3.1'

services:

  wordpress:
    image: wordpress:5.1.1
    environment:
      - WORDPRESS_DB_PASSWORD=secret
    ports:
      - 14080:80
    volumes:
      - wp-content:/var/www/html/wp-content:rw
      - ./:/var/www/html/wp-content/plugins/granular:rw

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    ports:
      - 14081:8080

  composer:
    image: composer
    user: 1000:1000
    volumes:
      - ./:/app

  phpunit:
    image: phpunit/phpunit:6.5.3
    user: 1000:1000
    volumes:
      - ./:/app

volumes:
  wp-content:
  mysql:
